### ISSUE TITLE
NextJS Server Side

### ISSUE THREAD

**Issue by alexevladgabriel** [juliusmarminge/t3-appdir#2]
Isn't NextJS server-side by default?
https://github.com/juliusmarminge/t3-appdir/blob/b94907d12cf7c4666322475c50064002d7807fef/src/app/actions.ts#LL1C14-L1C14

**Comment by juliusmarminge** [comment]
actions must have the directive explicitely for the compiler to recognize them as server actions: https://nextjs.org/docs/app/building-your-application/data-fetching/server-actions#creation
